apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: h2o
  name: h2o
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h2o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: h2o
        # io.kompose.service: h2o
    spec:
      containers:
      - image: h2o:ppc64le
        name: h2o
		imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
